newApp:
    replicaCount: 1
    image:
        repository: null
        tag: null
        pullPolicy: IfNotPresent
    service:
        name: newApp
        type: LoadBalancer
        externalPort: 8080
        internalPort: 8080
    resources:
        limits:
            cpu: 100m
            memory: 128Mi
        requests:
            cpu: 100m
            memory: 128Mi
newAppBlue:
    replicaCount: 1
    image:
        repository: null
        tag: staging-stable
        pullPolicy: IfNotPresent
    service:
        name: newApp-blue
        type: LoadBalancer
        externalPort: 8080
        internalPort: 8080
    resources:
        limits:
            cpu: 100m
            memory: 128Mi
        requests:
            cpu: 100m
            memory: 128Mi
newAppGreen:
    replicaCount: 1
    image:
        repository: null
        tag: null
        pullPolicy: IfNotPresent
    service:
        name: newApp-green
        type: LoadBalancer
        externalPort: 8080
        internalPort: 8080
    resources:
        limits:
            cpu: 100m
            memory: 128Mi
        requests:
            cpu: 100m
            memory: 128Mi
